
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `Northwind`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=KULTIS\SQLEXPRESS;Initial Catalog=Northwind;Integrated Security=True`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using ServiceStack.OrmLite;
using ServiceStack.DataAnnotations;
using ServiceStack.DesignPatterns.Model;

namespace ServiceStack.Northwind.ServiceModel.Types
{
    
	[Alias("Employees")]
    public partial class Employee : IHasId<int>    {
        [Alias("EmployeeID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string LastName { get; set;}
        [Required]
        public string FirstName { get; set;}
        public string Title { get; set;}
        public string TitleOfCourtesy { get; set;}
        public DateTime? BirthDate { get; set;}
        public DateTime? HireDate { get; set;}
        public string Address { get; set;}
        public string City { get; set;}
        public string Region { get; set;}
        public string PostalCode { get; set;}
        public string Country { get; set;}
        public string HomePhone { get; set;}
        public string Extension { get; set;}
        public string Notes { get; set;}
        public int? ReportsTo { get; set;}
        public string PhotoPath { get; set;}
    }
    
	[Alias("Categories")]
    public partial class Category : IHasId<int>    {
        [Alias("CategoryID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string CategoryName { get; set;}
        public string Description { get; set;}
    }
    
	[Alias("Customers")]
    public partial class Customer : IHasId<string>    {
        [Alias("CustomerID")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string CompanyName { get; set;}
        public string ContactName { get; set;}
        public string ContactTitle { get; set;}
        public string Address { get; set;}
        public string City { get; set;}
        public string Region { get; set;}
        public string PostalCode { get; set;}
        public string Country { get; set;}
        public string Phone { get; set;}
        public string Fax { get; set;}
    }
    
	[Alias("Shippers")]
    public partial class Shipper : IHasId<int>    {
        [Alias("ShipperID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string CompanyName { get; set;}
        public string Phone { get; set;}
    }
    
	[Alias("Suppliers")]
    public partial class Supplier : IHasId<int>    {
        [Alias("SupplierID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string CompanyName { get; set;}
        public string ContactName { get; set;}
        public string ContactTitle { get; set;}
        public string Address { get; set;}
        public string City { get; set;}
        public string Region { get; set;}
        public string PostalCode { get; set;}
        public string Country { get; set;}
        public string Phone { get; set;}
        public string Fax { get; set;}
        public string HomePage { get; set;}
    }
    
	[Alias("Orders")]
    public partial class Order : IHasId<int>    {
        [Alias("OrderID")]
        [AutoIncrement]
        public int Id { get; set;}
        public string CustomerID { get; set;}
        public int? EmployeeID { get; set;}
        public DateTime? OrderDate { get; set;}
        public DateTime? RequiredDate { get; set;}
        public DateTime? ShippedDate { get; set;}
        public int? ShipVia { get; set;}
        public decimal? Freight { get; set;}
        public string ShipName { get; set;}
        public string ShipAddress { get; set;}
        public string ShipCity { get; set;}
        public string ShipRegion { get; set;}
        public string ShipPostalCode { get; set;}
        public string ShipCountry { get; set;}
    }
    
	[Alias("Products")]
    public partial class Product : IHasId<int>    {
        [Alias("ProductID")]
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public string ProductName { get; set;}
        public int? SupplierID { get; set;}
        public int? CategoryID { get; set;}
        public string QuantityPerUnit { get; set;}
        public decimal? UnitPrice { get; set;}
        public short? UnitsInStock { get; set;}
        public short? UnitsOnOrder { get; set;}
        public short? ReorderLevel { get; set;}
        [Required]
        public bool Discontinued { get; set;}
    }
    
	[Alias("CustomerCustomerDemo")]
    public partial class CustomerCustomerDemo : IHasId<string>    {
        [Alias("CustomerID")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string CustomerTypeID { get; set;}
    }
    
	[Alias("Territories")]
    public partial class Territory : IHasId<string>    {
        [Alias("TerritoryID")]
        [Required]
        public string Id { get; set;}
        [Required]
        public string TerritoryDescription { get; set;}
        [Required]
        public int RegionID { get; set;}
    }
    
	[Alias("EmployeeTerritories")]
    public partial class EmployeeTerritory : IHasId<int>    {
        [Alias("EmployeeID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public string TerritoryID { get; set;}
    }
    
	[Alias("OrderDetails")]
    public partial class OrderDetail    {
        [AutoIncrement]
        public int Id { get; set;}
        [Required]
        public int OrderId { get; set;}
        [Required]
        public int ProductId { get; set;}
        [Required]
        public decimal UnitPrice { get; set;}
        [Required]
        public short Quantity { get; set;}
        [Required]
        public float Discount { get; set;}
    }
    
	[Alias("CustomerDemographics")]
    public partial class CustomerDemographic : IHasId<string>    {
        [Alias("CustomerTypeID")]
        [Required]
        public string Id { get; set;}
        public string CustomerDesc { get; set;}
    }
    
	[Alias("Regions")]
    public partial class Region : IHasId<int>    {
        [Alias("RegionID")]
        [Required]
        public int Id { get; set;}
        [Required]
        public string RegionDescription { get; set;}
    }
	
}

